# -*- coding: utf-8 -*-
"""Credit_card.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Moh0HW114OYJkoRjWQ5nMrOFxzHZXxBz
"""

# ==========================================
# CREDIT CARD FRAUD DETECTION PROJECT
# ==========================================

# Import Libraries

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

# ==========================================
# STEP 2 : DATA COLLECTION
# ==========================================

# Load Training Dataset

train_df = pd.read_csv('/content/fraudTrain.csv')

# Load Testing Dataset

test_df = pd.read_csv('/content/fraudTest.csv')

# Combine both datasets

df = pd.concat([train_df, test_df], ignore_index=True)

# Display First 5 Rows

print("First 5 Rows")
print(df.head())

# Dataset Shape

print("\nDataset Shape")
print(df.shape)

# Column Names

print("\nColumns in Dataset")
print(df.columns)

# ==========================================
# STEP 3 : DATA UNDERSTANDING
# ==========================================

# Dataset Information

print("\nDataset Information")
print(df.info())

# Missing Values

print("\nMissing Values")
print(df.isnull().sum())

# Statistical Summary

print("\nStatistical Summary")
print(df.describe())

# ==========================================
# STEP 4 : DATA CLEANING
# ==========================================

# Remove unnecessary columns

columns_to_drop = [
    'Unnamed: 0',
    'trans_date_trans_time',
    'cc_num',
    'first',
    'last',
    'street',
    'city',
    'state',
    'zip',
    'dob',
    'trans_num'
]

df.drop(columns=columns_to_drop,
        inplace=True,
        errors='ignore')

print("\nColumns After Cleaning")
print(df.columns)

# ==========================================
# STEP 5 : DATA PREPROCESSING
# ==========================================

# Convert categorical columns into numerical

label_encoder = LabelEncoder()

categorical_columns = [
    'merchant',
    'category',
    'gender',
    'job'
]

for col in categorical_columns:

    if col in df.columns:
        df[col] = label_encoder.fit_transform(
            df[col].astype(str)
        )

# Check Dataset After Encoding

print("\nDataset After Encoding")
print(df.head())

# ==========================================
# STEP 5.1 : HANDLE MISSING VALUES
# ==========================================

# Check missing values

print(df.isnull().sum())

# Fill missing numerical values with median

numerical_columns = df.select_dtypes(include=np.number).columns

for col in numerical_columns:
    df[col] = df[col].fillna(df[col].median())

# Fill missing categorical values with mode

categorical_columns = df.select_dtypes(include='object').columns

for col in categorical_columns:
    df[col] = df[col].fillna(df[col].mode()[0])

# Verify no missing values remain

print("\nMissing Values After Filling")
print(df.isnull().sum())

# ==========================================
# STEP 6 : EXPLORATORY DATA ANALYSIS
# ==========================================

# 1. Fraud vs Legit Transactions

plt.figure(figsize=(6,4))

sns.countplot(x='is_fraud', data=df)

plt.title('Fraud vs Legit Transactions')
plt.xlabel('is_fraud')
plt.ylabel('Count')

plt.show()

# 2. Transaction Amount Distribution

plt.figure(figsize=(8,5))

sns.histplot(df['amt'], bins=50, kde=True)

plt.title('Transaction Amount Distribution')
plt.xlabel('Transaction Amount')
plt.ylabel('Frequency')

plt.show()

# 3. Gender vs Fraud

plt.figure(figsize=(6,4))

sns.countplot(x='gender',
              hue='is_fraud',
              data=df)

plt.title('Gender vs Fraud')
plt.xlabel('Gender')
plt.ylabel('Count')

plt.show()

# 4. Fraud by Category

plt.figure(figsize=(12,6))

sns.countplot(x='category',
              hue='is_fraud',
              data=df)

plt.title('Transaction Category vs Fraud')

plt.xticks(rotation=90)

plt.show()

# 5. Correlation Heatmap

plt.figure(figsize=(12,8))

sns.heatmap(df.corr(numeric_only=True),
            cmap='coolwarm')

plt.title('Correlation Heatmap')

plt.show()

# ==========================================
# STEP 7 : DEFINE FEATURES AND TARGET
# ==========================================

# Feature Variables

X = df.drop('is_fraud', axis=1)

# Target Variable

y = df['is_fraud']

print("\nFeatures")
print(X.head())

print("\nTarget")
print(y.head())

# ==========================================
# STEP 8 : TRAIN TEST SPLIT
# ==========================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("\nTraining Data Shape")
print(X_train.shape)

print("\nTesting Data Shape")
print(X_test.shape)

# ==========================================
# STEP 9 : FEATURE SCALING
# ==========================================

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)

# ==========================================
# STEP 10 : MODEL BUILDING
# ==========================================

# ------------------------------------------
# LOGISTIC REGRESSION
# ------------------------------------------

log_model = LogisticRegression()

log_model.fit(X_train, y_train)

log_prediction = log_model.predict(X_test)

print("\n========== Logistic Regression ==========")

print("Accuracy:",
      accuracy_score(y_test,
                     log_prediction))

print(classification_report(
    y_test,
    log_prediction
))

# ------------------------------------------
# DECISION TREE
# ------------------------------------------

dt_model = DecisionTreeClassifier(
    random_state=42
)

dt_model.fit(X_train, y_train)

dt_prediction = dt_model.predict(X_test)

print("\n========== Decision Tree ==========")

print("Accuracy:",
      accuracy_score(y_test,
                     dt_prediction))

print(classification_report(
    y_test,
    dt_prediction
))

# ------------------------------------------
# RANDOM FOREST
# ------------------------------------------

rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

rf_model.fit(X_train, y_train)

rf_prediction = rf_model.predict(X_test)

print("\n========== Random Forest ==========")

print("Accuracy:",
      accuracy_score(y_test,
                     rf_prediction))

print(classification_report(
    y_test,
    rf_prediction
))

# ==========================================
# STEP 11 : CONFUSION MATRIX
# ==========================================

cm = confusion_matrix(y_test,
                      rf_prediction)

plt.figure(figsize=(6,4))

sns.heatmap(cm,
            annot=True,
            fmt='d',
            cmap='Blues')

plt.title('Confusion Matrix')
plt.xlabel('Predicted')
plt.ylabel('Actual')

plt.show()

# ==========================================
# STEP 12 : FEATURE IMPORTANCE
# ==========================================

importance = pd.DataFrame({
    'Feature': X.columns,
    'Importance': rf_model.feature_importances_
})

importance = importance.sort_values(
    by='Importance',
    ascending=False
)

print("\nFeature Importance")
print(importance.head(10))

# Plot Feature Importance

plt.figure(figsize=(10,6))

plt.barh(importance['Feature'][:10],
         importance['Importance'][:10])

plt.title('Top 10 Important Features')
plt.xlabel('Importance Score')
plt.ylabel('Features')

plt.gca().invert_yaxis()

plt.show()

# ==========================================
# STEP 13 : FINAL PREDICTION
# ==========================================

# Take One Sample Transaction

sample_data = X_test[0].reshape(1, -1)

# Predict Transaction

prediction = rf_model.predict(sample_data)

# Display Result

if prediction[0] == 1:
    print("\nFraud Transaction Detected")
else:
    print("\nLegitimate Transaction")

